name: Rust

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --verbose

    - name: Check for lints
      run: cargo clippy --verbose

    - name: Run tests
      run: cargo test --verbose
